# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: frontend-hpa
#   namespace: ecommerce
# spec:
#   scaleTargetRef:
#     apiVersion: argoproj.io/v1alpha1
#     kind: Rollout
#     name: frontend
#   minReplicas: 2
#   maxReplicas: 4
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 80
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: frontend-hpa
#   namespace: ecommerce
# spec:
#   scaleTargetRef:
#     apiVersion: argoproj.io/v1alpha1
#     kind: Rollout
#     name: frontend
#   minReplicas: 2
#   maxReplicas: 4
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 80
#   behavior:
#     scaleUp:
#       policies:
#       - type: Pods
#         value: 1
#         periodSeconds: 15
#       selectPolicy: Max
#       stabilizationWindowSeconds: 180  # 3분 동안 CPU 사용률을 평가
#     scaleDown:
#       policies:
      # - type: Pods
      #   value: 1
      #   periodSeconds: 15
      # selectPolicy: Max
      # stabilizationWindowSeconds: 60  # 1분 동안 CPU 사용률을 평가

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: ecommerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 4
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
      selectPolicy: Max
      stabilizationWindowSeconds: 90  # 3분 동안 CPU 사용률을 평가
    scaleDown:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
      selectPolicy: Max
      stabilizationWindowSeconds: 90  # 1분 동안 CPU 사용률을 평가
